-- Bind each Pro license to the first browser that activates it.
-- device_id is a random ID generated by the extension (not hardware info).
-- NULL = never activated yet; first validation binds it automatically.
-- Support reset = set device_id back to NULL in the dashboard.

alter table licenses add column if not exists device_id text;
alter table licenses add column if not exists device_bound_at timestamp with time zone;
